### ISSUE TITLE
Where can I find the EOP source IP addresses for inbound connections to SMTP servers?

### ISSUE THREAD

**Issue by diego-santacruz** [MicrosoftDocs/OfficeDocs-Enterprise#348] opened 2019-03-22 16:13 UTC
Before the switch to the WebService for IP addresses, the list of source IP addresses used by Exchange Online Protection to route emails to on-premises SMTP servers was given. 

The EOP doc at https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail still points to this page to get the list of IP addresses though.

Where can we find this information now? Without it I cannot continue to update the rules on my corporate firewall.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by guyyardeni** [comment] 2019-03-22 17:17
+1. The article calls out that inbound/hybrid connections aren't covered here but not where to find those.

**Comment by robmazz** [comment] 2019-03-25 15:27
@diego-santacruz and @guyyardeni - thanks for the feedback, I'll get this over to the Enterprise content team for clarification and action.

**Comment by Neckross** [comment] 2019-03-29 19:47
+2. We don't have a location to get the EOP IP's anymore.... other than grabbing it from (spf.protection.outlook.com) but should have a dedicated document for EOP IP addresses.

**Comment by JoeDavies-MSFT** [comment] 2019-04-02 15:24
@diego-santacruz and @Neckross I have forwarded this issue to the product team that owns these endpoints for their investigation. Closing this issue for now.

**Closed by JoeDavies-MSFT** 2019-04-02 15:24 UTC

**Comment by mtaggart99** [comment] 2019-04-09 20:29
@JoeDavies-MSFT - why would you close out this issue until the problem is fixed?  

I too have this issue and have opened a support case with MS, I also showed this thread to the tech I'm working with and he agreed with me that you shouldn't have closed it until it was fixed.

What's the latest status of this?  It affects a large amount of people ....

**Comment by JoeDavies-MSFT** [comment] 2019-04-11 14:54
@diego-santacruz @Neckross @mtaggart99   The addresses in the old article have been moved here: https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#exchange-online I will update the article cited above to link to this new location

**Comment by Neckross** [comment] 2019-04-11 18:50
@JoeDavies-MSFT - none of the EOP IP's are there (ex. 213 & 216 subnets)

**Comment by JoeDavies-MSFT** [comment] 2019-04-11 23:01
@Neckross These were removed. See this query for the web service: https://endpoints.office.com/changes/worldwide/2019010600?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7

The current list of EOP IP address ranges is here: https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#exchange-online

**Comment by mtaggart99** [comment] 2019-04-16 21:07
@JoeDavies-MSFT - the first link does not work properlly, everything comes up malformed.

The 2nd link is incorrect as well - there's nothing listed for EOP.

Also, if the old datacenter ranges were removed then why do they all still work?  

Please correct this issue.

**Comment by mtaggart99** [comment] 2019-04-17 14:47
@JoeDavies-MSFT -- also, you state the ranges are listed above, which ranges, there's many different groups of ranges for a wide range of things - it's not clear exactly what we are supposed to use.  

The previous range of IP's that we still use today (and work) are these in which I had retrieved for this link from March 13, 2019 - none of these are listed in your link provided:

https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/exchange-online-protection-ip-addresses
 
23.103.132.0/22
23.103.136.0/21
23.103.144.0/20
23.103.198.0/23
23.103.200.0/22
40.92.0.0/14
40.107.0.0/17
52.100.0.0/14
52.238.78.88/32
65.55.88.0/24
65.55.169.0/24
94.245.120.64/26
104.47.0.0/17
157.55.234.0/24
157.56.110.0/23
157.56.112.0/24
207.46.100.0/24
207.46.163.0/24
213.199.154.0/24
213.199.180.128/26
216.32.180.0/23

**Comment by Neckross** [comment] 2019-04-17 15:29
+1 to @mtaggart99 

@JoeDavies-MSFT - if you query spf.protection.outlook.com you'll see what we're talking about. Running a message trace or telnet to test mailflow in a hybrid environment where we typically lockdown port 25 to EOP IP's, you can see under it still using some of those IP's that are listed under SPF record. There's no documentation that list EOP IP list, we need that. The link you provided only list EXO.

**Comment by ewukow77** [comment] 2019-10-15 15:50
Has this been resolved? I am looking for the same information and making little progress.
