### ISSUE TITLE
Missing information for Office for PC

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-Enterprise#194] opened 2018-10-24 10:09 UTC
There used to be dedicated page for Office ProPlus apps for PC, but now the page is gone and there is no information for ProPlus on this page. When customers want to deploy ProPlus they do not know which exactly end points are needed. We need for PC the same page that is available for Mac https://docs.microsoft.com/pl-pl/office365/enterprise/network-requests-in-office-2016-for-mac.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/pl-pl/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2#microsoft-365-common-and-office-online)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment] 2018-10-25 13:22
@Larryngolog Thank you for this feedback

I will get this information over to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment] 2018-10-25 16:10
@Larryngolog I have forwarded your question to the product team owners, who will re-open this issue when they provide an answer.

**Comment by Larryngolog** [comment] 2018-10-25 20:45
Hi @pandrew1. I'm not sure where is this information stated. Do you mean that if customer wants to use just Office 365 ProPlus without using any other cloud services they need to allow all required addresses for Microsoft 365 Common and Office Online? It seems like it's too much just to use ProPlus and regulated customer oppose to having opening to so many addresses, especially if they do not want to use Office Online. For Mac each address is explained what it does, for M365 common we need to assume based on the URL.

**Comment by pandrew1** [comment] 2019-01-18 03:48
Hi @Larryngolog , Yes, most customers want to connect to all of Office 365 and that's what is provided. Enterprise customers with account management can still access the specific details for Office 365 ProPlus only under NDA.
Regards,
Paul

**Comment by pandrew1** [comment] 2019-01-18 03:50
Duplicate of #100

**Comment by mypil** [comment] 2019-04-09 15:36
@pandrew1 - Do you have any updates on this? Thanks.

**Comment by mypil** [comment] 2019-04-10 15:27
@officedocsbot assign @mypil

**Comment by mypil** [comment] 2019-04-15 12:18
@pandrew1 - We would like to follow up on this. Do you have any updates? Thanks.

**Comment by pandrew1** [comment] 2019-04-15 16:02
@mypil For Office 365 Pro Plus customers should configure network perimeter devices with endpoints in the Common service area. Configuration can be simplified by programmatically using our web service here: https://endpoints.office.com/endpoints/worldwide?serviceareas=common&clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7

**Comment by mypil** [comment] 2019-04-16 11:02
@Larryngolog - From our understanding, the issue you raised has been answered by pandrew1. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment] 2019-04-19 09:59
@officedocsbot close

**Closed by mypil** 2019-04-19 09:59 UTC
