### ISSUE TITLE
*.office.com is actually required.

### ISSUE THREAD

**Issue by MikeHynek** [MicrosoftDocs/OfficeDocs-Enterprise#272] opened 2019-01-03 21:06 UTC
In ID 78, the notes section says "Some Office 365 features require endpoints within these domains (including CDNs). Many specific FQDNs within these wildcards have been published recently as we work to either remove or better explain our guidance relating to these wildcards." I have found that *.office.com is necessary for autodiscover in outlook client to work properly. The autodiscover.outlook.com name redirects to, for example, autod.ms-acdc.office.com. On ID 78 are the following URLs: *.microsoft.com,*.msocdn.com,*.office.com,*.office.net,*.onmicrosoft.com.  Please explain why you consider this entry as not Required (Required=False). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by robmazz** [comment] 2019-01-07 15:37
@MikeHynek - thanks for the feedback, I'll get this over to the Enterprise content team.

**Comment by kelleyvice-msft** [comment] 2019-01-15 18:59
@MikeHynek - After reading your comments more carefully, it looks like you are talking about data in the web service itself rather than content in the referenced topic (https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service). I've confirmed that there have been no subsequent changes in the web service to mark *.office.com as required. I have submitted a request for clarification from the relevant PMs. -Kelley

**Comment by mypil** [comment] 2019-04-09 16:43
@MikeHynek - From our understanding, the issue has been answered by kelleyvice-msft. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment] 2019-04-10 15:23
@officedocsbot assign @mypil

**Comment by kelleyvice-msft** [comment] 2019-04-10 17:18
@MikeHynek - I've just been informed that there are endpoint updates scheduled to be published by the end of April that should resolve this issue. Apologies for the delay. I will close this ticket, but feel free to reopen it if you observe the same issues after 4/30. Thanks!

**Comment by MikeHynek** [comment] 2019-04-10 18:01
What do you mean by this?
"published by the end of April that should resolve this issue."

On ID 78 are the following URLs: .microsoft.com,.msocdn.com,.office.com,.office.net,.onmicrosoft.com. Please explain why you consider this entry as not Required (Required=False).


Mike Hynek
Senior Consultant | Business Productivity Cloud Solutions
Mobile: 608-444-1391 | Mike.Hynek@Microsoft.com<mailto:Mike.Hynek@Microsoft.com>
[http://mysignature/Images/Logos/L_Microsoft.png]

**Comment by kelleyvice-msft** [comment] 2019-04-10 18:41
@MikeHynek - I don't have visibility into the reason the required attribute is set to false on ID78, but the PM I work with told me this morning that there is a new set of autodiscover endpoints scheduled to be published to the web service on 4/29. There are multiple feature teams who publish their own endpoints, and it is sometimes difficult to establish information about the origin of endpoint values. However, the issue has been surfaced to the feature team who owns these endpoints, and my information is that the 4/29 update should resolve the autodiscover problem.

Sorry I don't have more detailed information for you, but I'll certainly let you know if I learn anything else that bears on this issue.

Thanks,
Kelley

**Comment by hmuchaku** [comment] 2019-05-07 02:42
@kelleyvice-msft 
I'm also in trouble with the same problem. ID 78 has not been modified yet.  Please check it.
{
    "id": 78,
    "serviceArea": "Common",
    "serviceAreaDisplayName": "Microsoft 365 Common and Office Online",
    "urls": [
      "*.microsoft.com",
      "*.msocdn.com",
      "*.office.com",
      "*.office.net",
      "*.onmicrosoft.com"
    ],
    "tcpPorts": "80,443",
    "expressRoute": false,
    "category": "Default",
    **"required": false,**
    "notes": "Some Office 365 features require endpoints within these domains (including CDNs). Many specific FQDNs within these wildcards have been published recently as we work to either remove or better explain our guidance relating to these wildcards."
  },

**Comment by kelleyvice-msft** [comment] 2019-05-07 15:46
@hmuchaku - Thanks for reaching out. To clarify, you are having problems with Outlook autodiscover because _.office.com_ is not set to "required": **true** in ID #78? I will bring this information back to the PMs and let them know there are still problems.

**Comment by kelleyvice-msft** [comment] 2019-05-07 15:50
@hmuchaku - also, can you confirm whether you have updated your whitelisted endpoints with the changes from 4/29/2019 (https://endpoints.office.com/changes/worldwide/2019032800?ClientRequestId=7059fad7-1027-4f4e-8b74-a17bec1c8ff1)? Thank you!

**Comment by kelleyvice-msft** [comment] 2019-05-07 16:48
@MikeHynek - Here is some additional information I received from the product group regarding URLs that redirect to CNAME records:

_URLs are published for the purposes of bypassing proxy server authentication, SSL break and inspect, and filtering. Client applications pass the original Internet FQDN to the proxy server along with the request. The proxy server does not evaluate any DNS redirects (also known as CNAME records) and hence we do not publish these. Use of CNAME records in this way is a common industry convention and supports operational requirements in running a large cloud service. We have also provided an FAQ on CNAME redirects in the DNS here: https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints#some-office-365-urls-point-to-cname-records-instead-of-a-records-in-the-dns-what-do-i-have-to-do-with-the-cname-records._ 

Please let me know if you're still encountering problems related to this issue. I would be interested in determining whether there is additional guidance we can provide to help mitigate this kind of problem.

Thanks, 
Kelley

**Comment by hmuchaku** [comment] 2019-05-08 01:44
@kelleyvice-msft 
Thank you for your help. 
In my case it is a little different from the problem with Mike.
I wanted to access "reports.office.com" via a proxy server.
The proxy server passes only the "required:true" url.
Because ID78 was mentioned in this issue, I thought that ID78 would be corrected from required:false to required:true.

**Comment by mypil** [comment] 2019-05-29 19:30
@kelleyvice-msft - Do you have any updates on this?

Thank you.

**Comment by mypil** [comment] 2019-06-04 07:48
@kelleyvice-msft - We would like to follow up. Do you have any updates on this?

cc: @LauraWi 

Thank you.

**Comment by kelleyvice-msft** [comment] 2019-06-04 15:03
@mypil - sorry, I just returned from vacation yesterday. There has been a fair bit of discussion around this - let me follow up and return to this issue with updated information if there is any. - Kelley

**Comment by mypil** [comment] 2019-06-12 08:00
@kelleyvice-msft - Do you have any updates on how we can close this issue?

Thank you.

**Comment by kelleyvice-msft** [comment] 2019-06-12 13:50
With respect to URLs in **id 78**, the notes section says "Some Office 365 features require endpoints within these domains (including CDNs)." In https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints, we also say, "If you're trying to use Office 365 and are finding third party services aren't accessible you'll want to ensure all FQDNs marked required or optional in this article are allowed through the proxy and firewall." For customers experiencing issues like @hmuchaku, the guidance at this time is to configure proxy devices to allow traffic to endpoints marked as _optional_.

I will close this issue and update our guidance to make this clearer.

**Closed by kelleyvice-msft** 2019-06-12 13:50 UTC
