### ISSUE TITLE
Applying Domain Restrictions

### ISSUE THREAD

**Issue by stewalshy** [MicrosoftDocs/OfficeDocs-Enterprise#733] opened 2020-03-02 08:53 UTC
Hi,

If we apply domain restrictions (at site, org or AAD level), do they revoke previous sharing of sites/files/folders with domains that are no longer allowed? Or does it just apply the restrictions to block future sharing with those domains?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb31720-7494-ab3f-6a3d-5c395649e75d
* Version Independent ID: 81c36ae8-fbaa-c411-4bd2-a4db98e249e1
* Content: [Microsoft 365 guest sharing settings reference](https://docs.microsoft.com/en-ie/Office365/Enterprise/microsoft-365-guest-settings#feedback)
* Content Source: [Enterprise/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-365-guest-settings.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by stewalshy** [comment] 2020-03-11 13:21
Hi, is there any feedback on this question?

**Comment by msbemba** [comment] 2020-03-16 07:10
@stewalshy Thank you for your feedback. By Design when we apply domain restrictions it will revoke the previous sharing with the domains that are no longer allowed.

Hope this  Helps!

Thanks
Sri

**Comment by mypil** [comment] 2020-03-21 22:51
@stewalshy  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Closed by mypil** 2020-03-21 22:51 UTC
