### ISSUE TITLE
URLs Incorrect

### ISSUE THREAD

**Issue by gavinmorrison** [MicrosoftDocs/OfficeDocs-Enterprise#129] opened 2018-08-29 09:09 UTC
The list of URLs available over ExpressRoute has changed since this article was written. This article now gives conflicting guidance to the more current article at https://support.office.com/en-gb/article/managing-office-365-endpoints-99cab9d4-ef59-4207-9f2b-3728eb46bf9a?ui=en-US&rs=en-GB&ad=GB#ID0EACAAA=2._Proxies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d6fb94-5858-e752-427e-9e35371fa4b1
* Version Independent ID: 54d9ca69-39cc-a89b-a9e9-12f4d14ee110
* Content: [Routing with ExpressRoute for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/routing-with-expressroute#deciding-which-applications-and-features-route-over-expressroute)
* Content Source: [Enterprise/routing-with-expressroute.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/routing-with-expressroute.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by denisebmsft** [comment] 2018-08-29 16:13
@gavinmorrison thank you for the feedback. We'll look into this ASAP.

**Comment by kelleyvice-msft** [comment] 2018-08-31 16:31
I'll get this resolved today.

**Comment by oualabadmins** [comment] 2018-09-04 15:54
I've been working on this; the issue is more complex than it seemed. All versions of the SOC topic https://support.office.com/en-gb/article/managing-office-365-endpoints-99cab9d4-ef59-4207-9f2b-3728eb46bf9a should redirect to the latest release on DMC: https://review.docs.microsoft.com/en-us/Office365/Enterprise/managing-office-365-endpoints. It appears that the EN-US version of the SOC topic (https://support.office.com/en-us/article/managing-office-365-endpoints-99cab9d4-ef59-4207-9f2b-3728eb46bf9a) redirects, but other localized versions do not. Working with Denise Vangel and Joe Davies on this issue.

I'm also checking for conflicts between https://review.docs.microsoft.com/en-us/Office365/Enterprise/managing-office-365-endpoints and the topic in question (https://docs.microsoft.com/en-us/office365/enterprise/routing-with-expressroute) and will work with Joe Davies to correct any issues there.

**Comment by oualabadmins** [comment] 2018-09-04 16:03
@gavinmorrison , can you please give me an example of conflicting guidance/URLs? Please compare the current version of the **Managing Office 365 endpoints** article (https://review.docs.microsoft.com/en-us/Office365/Enterprise/managing-office-365-endpoints) with https://docs.microsoft.com/en-us/office365/enterprise/routing-with-expressroute#deciding-which-applications-and-features-route-over-expressroute. See my above comment for information about redirection issues; I think the version of the Managing Office 365 endpoints article you are referring to is out of date and should be redirected.

**Comment by kelleyvice-msft** [comment] 2018-09-17 16:13
We have found that after migrating this content to docs.microsoft.com, localized versions of the original topic were not being redirected. This is being fixed, so closing the issue. @gavinmorrison feel free to reopen if there are still issues, but also note that we are planning significant changes to several O365 networking articles, and will be ensuring that guidance is consistent across all topics.

**Closed by kelleyvice-msft** 2018-09-17 16:13 UTC
